eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# Account Service - consultas idempotentes
resilience4j.circuitbreaker.instances.accountService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.accountService.sliding-window-size=5
resilience4j.circuitbreaker.instances.accountService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.accountService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.accountService.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=500ms

resilience4j.bulkhead.instances.accountService.max-concurrent-calls=5
resilience4j.bulkhead.instances.accountService.max-wait-duration=0

# Customer Service - GET idempotente / PUT sin Retry
resilience4j.circuitbreaker.instances.customerService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.customerService.sliding-window-size=5
resilience4j.circuitbreaker.instances.customerService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.customerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.customerService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.customerService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.customerService.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.customerService.max-attempts=3
resilience4j.retry.instances.customerService.wait-duration=500ms

resilience4j.bulkhead.instances.customerService.max-concurrent-calls=5
resilience4j.bulkhead.instances.customerService.max-wait-duration=0
