# ========================================
# PostgreSQL
# ========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_legacy
spring.datasource.username=matiaszuniga
spring.datasource.password=

spring.batch.jdbc.initialize-schema=always


# ========================================
# HikariCP
# ========================================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000


# ========================================
# Configuración Batch
# ========================================

batch.chunk-size=5
batch.skip-limit=10
batch.retry-limit=3


# ========================================
# Paralelismo
# ========================================

batch.executor.core-pool-size=3
batch.executor.max-pool-size=3
batch.executor.queue-capacity=10