spring.application.name=bff-web
server.port=8441

bank.core.base-url=http://localhost:8080

server.ssl.enabled=true
server.ssl.key-store=classpath:bff-local.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-local