# ==========================================
# BFF - Banco XYZ
# ==========================================

spring.application.name=bank-bff

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_legacy
spring.datasource.username=matiaszuniga
spring.datasource.password=

# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true