# ==========================================
# Procesos Batch - Banco XYZ
# ==========================================

spring.application.name=bank-batch

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_legacy
spring.datasource.username=matiaszuniga
spring.datasource.password=

# Spring Batch
spring.batch.jdbc.initialize-schema=always

# Procesamiento
batch.chunk-size=5
batch.skip-limit=10
batch.retry-limit=3

# Paralelismo
batch.executor.core-pool-size=2
batch.executor.max-pool-size=2
batch.executor.queue-capacity=10

# Particionamiento
batch.partition.grid-size=2