spring.application.name=bff-atm
server.port=8443

spring.config.import=configserver:http://localhost:8888

server.ssl.enabled=true
server.ssl.key-store=classpath:bff-local.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-local